models:
  - name: stg_orders
    description: "Staging layer for orders data. Enriches raw orders with customer names and derives business-relevant columns like order year"
    columns:
      - name: o_orderkey
        description: "Unique identifier for each order"
        tests:
          - not_null
          - unique
          - relationships:
              to: source('tpch', 'orders')
              field: o_orderkey
      - name: o_custkey
        description: "Foreign key linking to customer table"
        tests:
          - not_null
          - relationships:
              to: source('tpch', 'customer')
              field: c_custkey
      - name: customer_name
        description: "Customer name from customer master data"
        tests:
          - not_null
      - name: o_orderdate
        description: "Date when the order was placed"
        tests:
          - not_null
      - name: order_year
        description: "Year extracted from order date for time-based analysis"
        tests:
          - not_null
      - name: total_price
        description: "Total price of the order"

  - name: customer_revenue
    description: "Aggregated customer revenue calculated by summing extended prices with discounts applied. Business logic: Revenue = SUM(extended_price * (1 - discount)) for each customer."
    columns:
      - name: o_custkey
        description: "Customer identifier"
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('stg_orders')
              field: o_custkey
      - name: customer_name
        description: "Customer name"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated by this customer across all orders"
        tests:
          - not_null
  
  - name: nation_order_summary
    description: "Nation-level summary showing order volume and customer count. Business logic: Groups orders by nation to understand geographic distribution of business activity."
    columns:
      - name: nation_name
        description: "Name of the nation"
        tests:
          - not_null
      - name: num_customers
        description: "Count of distinct customers from this nation who have placed orders"
        tests:
          - not_null
      - name: num_orders
        description: "Total number of orders placed by customers from this nation"
        tests:
          - not_null
